/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import domainmodels.HoaDon;
import domainmodels.HoaDonChiTiet;
import domainmodels.KhachHang;
import domainmodels.NguoiDung;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import service.HoaDonChiTietService;
import service.HoaDonService;
import service.KhachHangService;
import service.NguoiDungService;
import service.SachService;
import serviceimpl.HoaDonChiTietServiceimpl;
import serviceimpl.HoaDonServiceIMpl;
import serviceimpl.KhachHangServiceImpl;
import serviceimpl.NguoiDungServiceImpl;
import serviceimpl.SachServiceimpl;
import viewmodels.HoaDonfinalViewModels;
import viewmodels.SachViewModels;
import viewmodels.SanPhamViewModels;

/**
 *
 * @author User
 */
public class UIBanHang extends javax.swing.JFrame {

    /**
     * Creates new form UIBanHang
     */
    private SachService sachService = new SachServiceimpl();
    List<SanPhamViewModels> listGioHang = new ArrayList<>();
    private KhachHangService khachHangService = new KhachHangServiceImpl();
    private HoaDonService hoaDonService = new HoaDonServiceIMpl();
    private HoaDonChiTietService hoaDonChiTietService = new HoaDonChiTietServiceimpl();
    private NguoiDungService nguoiDungService = new NguoiDungServiceImpl();

    public UIBanHang(String maNguoiDung, String tenNguoiDung) {
        initComponents();
        txt_maNdung.setText(maNguoiDung);
        txt_tenNgDung.setText(tenNguoiDung);
        loadTableAll(this.sachService.getAll());
        addCBBKH(khachHangService.getDangHD());
        AutoCompleteDecorator.decorate(cbb_khachHang);
        AutoCompleteDecorator.decorate(cbb_khuyenMai);

    }

    // ham lay ra thòi gian hien tai
    private String getDate() {
        // lay ra ngay hien tai
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        return dtf.format(now);
    }

    public void inBill() {

    }

    private HoaDon getHoaDon() {
        char idkh = cbb_khachHang.getSelectedItem().toString().charAt(0);
        String mandung = txt_maNdung.getText();
        String idnd = String.valueOf(nguoiDungService.getOne(mandung).getId());
        Double tongTien = Double.parseDouble(txt_tongTien.getText());
        Double khachCanTra = Double.parseDouble(txt_khachCanTra.getText());
        String ngayTao = this.getDate();
        int trangThai = 0;
        HoaDon hoaDon = new HoaDon(idnd, idnd, tongTien, khachCanTra, ngayTao, trangThai);
        return hoaDon;
    }

    private void addCBBKH(List<KhachHang> listKH) {
        DefaultComboBoxModel cbbKH = (DefaultComboBoxModel) cbb_khachHang.getModel();
        for (KhachHang khachHang : listKH) {
            cbbKH.addElement(khachHang.getTen() + "-" + khachHang.getSoDt() + "-" + khachHang.getId());
        }
        cbbKH.setSelectedItem("Khách Lẻ-0-1");
    }

    private void loadTableAll(List<SachViewModels> list) {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tb_listSach.getModel();
        defaultTableModel.setRowCount(0);
        for (int i = 0; i < list.size(); i++) {
            defaultTableModel.addRow(new Object[]{
                i + 1,
                list.get(i).getId(),
                list.get(i).getMa(),
                list.get(i).getTenSach(),
                list.get(i).getTenTheLoai(),
                list.get(i).getTenTacGia(),
                list.get(i).getGiaBan(),
                list.get(i).getTenNXB(),
                list.get(i).getMoTa(),});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_gioHang = new javax.swing.JTable();
        btn_xoaKhoiDonHang = new javax.swing.JButton();
        txt_soLuongSua = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        panel_Sach = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_listSach = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_searchText = new javax.swing.JTextField();
        btn_find = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_thanhToan = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cbb_khachHang = new javax.swing.JComboBox<>();
        txt_tongTien = new javax.swing.JTextField();
        txt_khachCanTra = new javax.swing.JTextField();
        cbb_khuyenMai = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txt_giamGia = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_maNdung = new javax.swing.JTextField();
        txt_tenNgDung = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tb_gioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Mã Sách", "Tên Sách", "Số lượng", "Đơn Giá", "Thành tiền"
            }
        ));
        jScrollPane2.setViewportView(tb_gioHang);

        btn_xoaKhoiDonHang.setText("Xóa khỏi đơn hàng");
        btn_xoaKhoiDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaKhoiDonHangActionPerformed(evt);
            }
        });

        jButton3.setText("Sửa sổ lượng");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(txt_soLuongSua, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_xoaKhoiDonHang)
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_xoaKhoiDonHang)
                    .addComponent(txt_soLuongSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(156, 156, 156))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 300));

        panel_Sach.setBackground(new java.awt.Color(255, 255, 255));

        tb_listSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "ID", "Mã Sách", "Tên Sách", "Thể Loại", "Tác Giả", "Giá Bán", "Nhà Xuất Bản", "Mô tả"
            }
        ));
        tb_listSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_listSachMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb_listSach);

        jButton5.setText("Trước");

        jButton6.setText("Sau");

        javax.swing.GroupLayout panel_SachLayout = new javax.swing.GroupLayout(panel_Sach);
        panel_Sach.setLayout(panel_SachLayout);
        panel_SachLayout.setHorizontalGroup(
            panel_SachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_SachLayout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jButton5)
                .addGap(63, 63, 63)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_SachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_SachLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panel_SachLayout.setVerticalGroup(
            panel_SachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_SachLayout.createSequentialGroup()
                .addContainerGap(289, Short.MAX_VALUE)
                .addGroup(panel_SachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap())
            .addGroup(panel_SachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_SachLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(35, 35, 35)))
        );

        jPanel1.add(panel_Sach, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 375, -1, -1));

        jButton1.setText("Dang Xuat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 610, -1, -1));

        jLabel1.setText("Tên Người Dùng");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 580, 100, -1));

        jLabel2.setText("Chi Tiết Đơn Hàng");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 123, -1));

        txt_searchText.setText("Tìm kiếm theo tên hoặc mã");
        jPanel1.add(txt_searchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 234, -1));

        btn_find.setText("Tìm kiếm");
        btn_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_findActionPerformed(evt);
            }
        });
        jPanel1.add(btn_find, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Tổng Tiền Dự Tính");

        jLabel4.setText("Khuyến Mại");

        jLabel5.setText("Khách Cần trả");

        btn_thanhToan.setText("Thanh toán");
        btn_thanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thanhToanActionPerformed(evt);
            }
        });

        jButton8.setText("Hủy Đơn Hàng");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel6.setText("Khách Hàng");

        cbb_khachHang.setEditable(true);

        txt_tongTien.setEnabled(false);
        txt_tongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tongTienActionPerformed(evt);
            }
        });

        txt_khachCanTra.setEnabled(false);

        cbb_khuyenMai.setEditable(true);
        cbb_khuyenMai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbb_khuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_khuyenMaiActionPerformed(evt);
            }
        });

        jLabel8.setText("Giảm Giá");

        txt_giamGia.setEnabled(false);

        jButton9.setText("Thêm khách hàng");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton2.setText("làm mới");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_khachCanTra, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_giamGia, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_tongTien, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbb_khuyenMai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2)
                                        .addContainerGap())
                                    .addComponent(cbb_khachHang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_thanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_tongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbb_khuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_giamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_khachCanTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbb_khachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(btn_thanhToan)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addGap(26, 26, 26))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(761, 40, 370, 450));

        jLabel7.setText("Mã Người Dùng");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 550, 100, -1));

        txt_maNdung.setEnabled(false);
        jPanel1.add(txt_maNdung, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 550, 150, -1));

        txt_tenNgDung.setEnabled(false);
        jPanel1.add(txt_tenNgDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 580, 150, -1));

        jButton7.setText("Quản Lý");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 610, -1, -1));

        jButton4.setText("Tất cả sản phẩm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1197, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int row = tb_gioHang.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Hay chons an pham de cap nhat so luong!");
            return;
        }
        String id = tb_gioHang.getValueAt(row, 0).toString();
        String soLuongSuaStr = txt_soLuongSua.getText();
        if (isPositiveInteger(soLuongSuaStr) == false) {
            JOptionPane.showMessageDialog(this, "Ban nhap sai so luong!");
            return;
        }
        int soLuongSua = Integer.parseInt(soLuongSuaStr);
        for (SanPhamViewModels sanPhamViewModels : listGioHang) {
            if (soLuongSua > 0) {
                if (sanPhamViewModels.getId().equalsIgnoreCase(id)) {
                    sanPhamViewModels.setSoLuong(soLuongSua);
                    break;
                }
            } else if (soLuongSua == 0) {
                if (sanPhamViewModels.getId().equalsIgnoreCase(id)) {
                    listGioHang.remove(sanPhamViewModels);
                    break;
                }
            }

        }
        loadTableGioHang(listGioHang);


    }//GEN-LAST:event_jButton3ActionPerformed
    public static boolean isPositiveInteger(String input) {
        try {
            // Chuyển chuỗi đầu vào thành số nguyên
            int num = Integer.parseInt(input);
            // Kiểm tra số nguyên có lớn hơn 0 hay không
            if (num >= 0) {
                return true; // Là số nguyên dương
            } else {
                return false; // Không là số nguyên dương
            }
        } catch (NumberFormatException e) {
            // Nếu không thể chuyển đổi chuỗi thành số nguyên, đây không phải là số nguyên dương
            return false;
        }
    }
    private void tb_listSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_listSachMouseClicked
        // TODO add your handling code here:

        int row = tb_listSach.getSelectedRow();
        String id = tb_listSach.getValueAt(row, 1).toString();
        String ma = tb_listSach.getValueAt(row, 2).toString();
        String ten = tb_listSach.getValueAt(row, 3).toString();
        int soLuong = 1;

        double giaBan = Double.parseDouble(tb_listSach.getValueAt(row, 6).toString());
        SanPhamViewModels sach = new SanPhamViewModels(id, ma, ten, giaBan, soLuong);
        boolean daTangSoLuong = false;
        for (SanPhamViewModels s : listGioHang) {
            if (s.getId().equalsIgnoreCase(sach.getId())) {
                s.setSoLuong(s.getSoLuong() + 1);
                daTangSoLuong = true;
                break;
            }
        }

        if (!daTangSoLuong) {
            sach.setSoLuong(1);
            listGioHang.add(sach);
        }

        loadTableGioHang(listGioHang);
        // sau khi load len giohang, ta se tinh tien


    }//GEN-LAST:event_tb_listSachMouseClicked

    private void btn_thanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thanhToanActionPerformed
        // TODO add your handling code here:
//         them hoa don
        if (tb_gioHang.getRowCount() <= 0) {
            JOptionPane.showMessageDialog(this, "Hãy chọn sách!");
            return;
        }
        int xacNhanThnahToan = JOptionPane.showConfirmDialog(this, "Xác nhận thanh toán!", "thanh toAN", JOptionPane.YES_NO_OPTION);
        if (xacNhanThnahToan != JOptionPane.YES_OPTION) {
            return;
        }
        HoaDon hoadon = this.getHoaDon();
        int idhoaDon = this.hoaDonService.insert(hoadon);
//         lấy ra mã hóa đơn để in hóa đơn
        HoaDonfinalViewModels hdon = this.hoaDonService.getonewithid(idhoaDon);
        String maHD = hdon.getMa();

// them vao hoa don chi tiet
        for (int i = 0; i < tb_gioHang.getRowCount(); i++) {
            String idSach = tb_gioHang.getValueAt(i, 0).toString();
            int soluong = Integer.parseInt(tb_gioHang.getValueAt(i, 3).toString());
            double donGia = Double.parseDouble(tb_gioHang.getValueAt(i, 4).toString());
            double thanhtien = Double.parseDouble(tb_gioHang.getValueAt(i, 5).toString());
            HoaDonChiTiet hoaDonChiTiet = new HoaDonChiTiet(idSach, donGia, soluong, thanhtien);
            this.hoaDonChiTietService.insert(hoaDonChiTiet, String.valueOf(idhoaDon));
        }
        int traLoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn in hóa đơn không", "In Hóa Đơn", JOptionPane.YES_NO_OPTION);
        if (traLoi == JOptionPane.YES_OPTION) {
            // Tạo một đối tượng JDialog
            JDialog dialog = new JDialog();
            dialog.setTitle("Thông tin thanh toán");
            dialog.setSize(400, 300);

            // Tạo một JTextArea
            JTextArea b = new JTextArea();
            b.setEditable(false); // Có thể chỉnh sửa nội dung trong JTextArea hay không
            dialog.add(b, BorderLayout.CENTER); // Đưa JTextArea vào vị trí trung tâm của JDialog

            // them noi dung bill vao day
            b.setText(b.getText() + "                                        Cửa Hàng Sach \n");
            b.setText(b.getText() + "-------------------------------------------------------------------------------\n");
            b.setText(b.getText() + "                                        Mã Hóa Đơn " + maHD + "\n");
            b.setText(b.getText() + "-------------------------------------------------------------------------------\n");
            b.setText(b.getText() + "  Sản Phẩm \tSố Lượng \tGiá \tThành Tiền" + "\n");
            b.setText(b.getText() + "--------------------------------------------------------------------------------\n");

            DefaultTableModel df = (DefaultTableModel) tb_gioHang.getModel();

            // Lấy thông tin sản phẩm từ bảng
            for (int i = 0; i < tb_gioHang.getRowCount(); i++) {
                String Name = df.getValueAt(i, 2).toString();
                String Qty = df.getValueAt(i, 3).toString();
                String Price = df.getValueAt(i, 4).toString();
                String Total = df.getValueAt(i, 5).toString();

                // Kiểm tra độ dài của tên sản phẩm
                if (Name.length() > 10) {
                    Name = Name.substring(0, 10) + "..."; // Giới hạn tên sản phẩm chỉ hiển thị 10 ký tự
                }

                b.setText(b.getText() + "  " + Name + "\t" + Qty + "\t" + Price + "\t" + Total + "\n");
            }

            b.setText(b.getText() + "--------------------------------------------------------------------------------\n");
            b.setText(b.getText() + "Tổng Tiền : \t\t\t" + txt_tongTien.getText() + "\n");
            b.setText(b.getText() + "--------------------------------------------------------------------------------\n");
            b.setText(b.getText() + "Cảm ơn quý khách!" + "\n");

            // Tạo một JButton
            JButton btnIn = new JButton("In Hóa Đơn");
            btnIn.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    try {
                        b.print();
                    } catch (PrinterException ex) {
                        Logger.getLogger(UIBanHang.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });
            dialog.add(btnIn, BorderLayout.SOUTH); // Đưa JButton vào vị trí dưới cùng của JDialog

            // Hiển thị JDialog
            dialog.setVisible(true);
        }

        listGioHang.clear();
        loadTableGioHang(listGioHang);

    }//GEN-LAST:event_btn_thanhToanActionPerformed

    private void btn_xoaKhoiDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaKhoiDonHangActionPerformed
        int row = tb_gioHang.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Hay chons an pham de cap nhat so luong!");
            return;
        }
        String id = tb_gioHang.getValueAt(row, 0).toString();

        for (SanPhamViewModels sanPhamViewModels : listGioHang) {
            if (sanPhamViewModels.getId().equalsIgnoreCase(id)) {
                listGioHang.remove(sanPhamViewModels);
                break;
            }
        }
        loadTableGioHang(listGioHang);        // TODO add your handling code here:

    }//GEN-LAST:event_btn_xoaKhoiDonHangActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String maNdung = txt_maNdung.getText();
        NguoiDung ng = this.nguoiDungService.getOne(maNdung);
        String tenNdung = txt_tenNgDung.getText();

        if (ng.getChucVu().equalsIgnoreCase("Quản Lý")) {
            CuaSoChinh csh = new CuaSoChinh(maNdung, tenNdung);
            csh.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "ban không thể vào quản lý!");
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void txt_tongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tongTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tongTienActionPerformed

    private void cbb_khuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_khuyenMaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbb_khuyenMaiActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if (tb_gioHang.getRowCount() <= 0) {
            JOptionPane.showMessageDialog(this, "Đơn hàng trống trơn, không có gì để hủy!!");
            return;
        }
        int traLoi = JOptionPane.showConfirmDialog(this, "Bạn có hủy đơn hàng này không", "Hủy đơn", JOptionPane.YES_NO_OPTION);
        if (traLoi == JOptionPane.YES_OPTION) {
            listGioHang.clear();
            loadTableGioHang(listGioHang);
        }


    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int traLoi = JOptionPane.showConfirmDialog(this, "Bạn muốn đăng xuất chứu?", "Đăng xuất", JOptionPane.YES_NO_OPTION);
        if (traLoi == JOptionPane.YES_OPTION) {
            this.dispose();
            UIDangNhap dangNhap = new UIDangNhap();
            dangNhap.setVisible(true);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findActionPerformed
        // TODO add your handling code here:
        String ten = txt_searchText.getText();
        loadTableAll(this.sachService.search(ten));
    }//GEN-LAST:event_btn_findActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        loadTableAll(this.sachService.getAll());

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        UIKhachHang kh = new UIKhachHang(); // Khởi tạo đối tượng JFrame con
        kh.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE); // Chỉ định hành động khi JFrame con đóng
        kh.setVisible(true); // Hiển thị JFrame con
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        addCBBKH(khachHangService.getDangHD());

    }//GEN-LAST:event_jButton2ActionPerformed
    private void loadTableGioHang(List<SanPhamViewModels> list) {

        DefaultTableModel defaultTableModel = (DefaultTableModel) tb_gioHang.getModel();
        defaultTableModel.setRowCount(0);
        for (int i = 0; i < list.size(); i++) {
            defaultTableModel.addRow(new Object[]{
                list.get(i).getId(), list.get(i).getMa(), list.get(i).getTen(), list.get(i).getSoLuong(), list.get(i).getGiaBan(),
                list.get(i).getSoLuong() * list.get(i).getGiaBan()
            });
        }
        DefaultTableModel defaultTableModelGioHang = (DefaultTableModel) tb_gioHang.getModel();
        double tongTien = tinhTongThanhTien(defaultTableModelGioHang);
        txt_tongTien.setText(Double.toString(tongTien));
        txt_khachCanTra.setText(Double.toString(tongTien));
    }

    public double tinhTongThanhTien(DefaultTableModel model) {
        double tongThanhTien = 0.0;

        for (int i = 0; i < model.getRowCount(); i++) {
            double thanhTien = (double) model.getValueAt(i, 5); // Lấy giá trị của cột thành tiền (chỉ số 4)
            tongThanhTien += thanhTien;
        }
        return tongThanhTien;
    }
// keim tra sach da co tỏng list hay chua

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        //</editor-fold>
        String maNguoiDung = "Mã người dùng"; // Thay thế bằng mã người dùng thực tế
        String tenNguoiDung = "Tên người dùng"; // Thay thế bằng tên người dùng thực tế

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UIBanHang(maNguoiDung, tenNguoiDung).setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_find;
    private javax.swing.JButton btn_thanhToan;
    private javax.swing.JButton btn_xoaKhoiDonHang;
    private javax.swing.JComboBox<String> cbb_khachHang;
    private javax.swing.JComboBox<String> cbb_khuyenMai;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panel_Sach;
    private javax.swing.JTable tb_gioHang;
    private javax.swing.JTable tb_listSach;
    private javax.swing.JTextField txt_giamGia;
    private javax.swing.JTextField txt_khachCanTra;
    private javax.swing.JTextField txt_maNdung;
    private javax.swing.JTextField txt_searchText;
    private javax.swing.JTextField txt_soLuongSua;
    private javax.swing.JTextField txt_tenNgDung;
    private javax.swing.JTextField txt_tongTien;
    // End of variables declaration//GEN-END:variables
}
