/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import domainmodels.NguoiDung;
import javax.swing.JOptionPane;
import service.NguoiDungService;
import serviceimpl.NguoiDungServiceImpl;

/**
 *
 * @author User
 */
public class UIDangNhap extends javax.swing.JFrame {

    /**
     * Creates new form UIDangNhap
     */
    private NguoiDungService dungService = new NguoiDungServiceImpl();
    private String maNguoiDung;
    private String tenNguoiDung;

    public UIDangNhap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_pass = new javax.swing.JPasswordField();
        btn_loginbanHang = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btn_loginQuanLy = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("User name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));
        jPanel1.add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 264, -1));

        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        txt_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passKeyPressed(evt);
            }
        });
        jPanel1.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 264, -1));

        btn_loginbanHang.setText("Bán Hàng");
        btn_loginbanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginbanHangActionPerformed(evt);
            }
        });
        jPanel1.add(btn_loginbanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 180, -1, -1));

        jButton2.setText("Đổi Mật Khẩu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 110, -1));

        jButton3.setText("Thoát");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 80, -1));

        btn_loginQuanLy.setText("Quản Lý");
        btn_loginQuanLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginQuanLyActionPerformed(evt);
            }
        });
        jPanel1.add(btn_loginQuanLy, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 103, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Đăng Nhập");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passKeyPressed

    }//GEN-LAST:event_txt_passKeyPressed
    private NguoiDung getData() {
        String ma = txt_user.getText().trim();
        String matKhau = txt_pass.getText().trim();
        if (ma.equals("") || matKhau.equals("")) {
            JOptionPane.showMessageDialog(this, "Chua nhap tai khoan hoac mat khau!");
            return null;
        } else {
            NguoiDung ng = new NguoiDung(ma, matKhau);
            return ng;
        }
    }
    private void btn_loginbanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginbanHangActionPerformed
        // TODO add your handling code here:
        String ma = txt_user.getText().trim();
        String matKhau = txt_pass.getText().trim();
        if (ma.equals("") || matKhau.equals("")) {
            JOptionPane.showMessageDialog(this, "Chua nhap tai khoan hoac mat khau!");
            return;
        }
        if (this.dungService.validate(ma, matKhau) == true) {
            // mo ui ban hang
            NguoiDung ndung = this.dungService.getOne(ma);
            if (ndung.getTrangThai() == 1) {
                JOptionPane.showMessageDialog(this, "tai Khoan da ngung hoat dong!");
                return;
            }
            this.maNguoiDung = ndung.getMa();
            this.tenNguoiDung = ndung.getHoTen();
            UIBanHang banHang = new UIBanHang(this.maNguoiDung, this.tenNguoiDung);
            banHang.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Dang Nhap That Bai!");
        }
    }//GEN-LAST:event_btn_loginbanHangActionPerformed

    private void btn_loginQuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginQuanLyActionPerformed
        // TODO add your handling code here:
        String ma = txt_user.getText().trim();
        String matKhau = txt_pass.getText().trim();
        if (ma.equals("") || matKhau.equals("")) {
            JOptionPane.showMessageDialog(this, "Chua nhap tai khoan hoac mat khau!");
            return;
        }
        if (this.dungService.validate(ma, matKhau) == true) {
            NguoiDung ndung = this.dungService.getOne(ma);
            if (ndung.getTrangThai() == 1) {
                JOptionPane.showMessageDialog(this, "tai Khoan da ngung hoat dong!");
                System.out.println("Ban khong  the vao quan ly !");
                return;
            }
            if (ndung.getChucVu().equalsIgnoreCase("Nhân Viên")) {
                JOptionPane.showMessageDialog(this, "Bạn không thể vào quản lý nhé!");
                System.out.println("Ban khong  the vao quan ly !");
                return;
            } else {
                this.maNguoiDung = ndung.getMa();
                this.tenNguoiDung = ndung.getHoTen();
                CuaSoChinh cuaSoChinh = new CuaSoChinh(this.maNguoiDung, this.tenNguoiDung);
                cuaSoChinh.setVisible(true);
                this.dispose();
            }

        } else {
            JOptionPane.showMessageDialog(this, "Dang Nhap That Bai!");
        }
    }//GEN-LAST:event_btn_loginQuanLyActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        UIDangKi dangKi = new UIDangKi();
        dangKi.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIDangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_loginQuanLy;
    private javax.swing.JButton btn_loginbanHang;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
