/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import domainmodels.HoaDonChiTiet;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import service.HoaDonChiTietService;
import service.HoaDonService;
import serviceimpl.HoaDonChiTietServiceimpl;
import serviceimpl.HoaDonServiceIMpl;
import viewmodels.HoaDonChiTietViewModels;
import viewmodels.HoaDonViewModels;
import viewmodels.HoaDonfinalViewModels;

/**
 *
 * @author User
 */
public class UIHoaDon extends javax.swing.JFrame {

    /**
     * Creates new form UIHoaDon
     */
    private HoaDonService hoaDonService = new HoaDonServiceIMpl();
    private HoaDonChiTietService chiTietService = new HoaDonChiTietServiceimpl();

    public UIHoaDon() {
        super("UIHoaDon");
        initComponents();
        buttongourp();
        loadTableHoaDon(this.hoaDonService.getAll(this.getDate()));
    }

    private void buttongourp() {
        ButtonGroup btn = new ButtonGroup();
        btn.add(rd_otherDay);
        btn.add(rd_today);
        rd_today.setSelected(true);
        startDate.setEnabled(false);
        enDate.setEnabled(false);
        btn_timNgay.setEnabled(false);
    }

    private String getDate() {
        // lay ra ngay hien tai
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        return dtf.format(now);
    }

    private void loadTableHoaDon(List<HoaDonfinalViewModels> list) {
        DefaultTableModel tbHHoaDonModel = (DefaultTableModel) tb_hoaDon.getModel();
        tbHHoaDonModel.setRowCount(0);
        for (HoaDonfinalViewModels hoaDonViewModels : list) {
            tbHHoaDonModel.addRow(new Object[]{
                hoaDonViewModels.getId(),
                hoaDonViewModels.getMa(),
                hoaDonViewModels.getTongTien(),
                0,
                hoaDonViewModels.getKhachCanTra(),
                hoaDonViewModels.getNgayTao(),
                hoaDonViewModels.getTenNguoiDung()
            });
        }
    }

    private void loadHoadonChiTiet(List<HoaDonChiTietViewModels> list) {
        DefaultTableModel tbHHoaDonModel = (DefaultTableModel) tb_hoaDonCt.getModel();
        tbHHoaDonModel.setRowCount(0);
        for (HoaDonChiTietViewModels hoaDonctViewModels : list) {
            tbHHoaDonModel.addRow(new Object[]{
                hoaDonctViewModels.getMa(),
                hoaDonctViewModels.getTenSach(),
                hoaDonctViewModels.getSoLuong(),
                hoaDonctViewModels.getDonGia(),
                hoaDonctViewModels.getThanhTien(),});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_hoaDon = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_hoaDonCt = new javax.swing.JTable();
        btnXuatfile = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        startDate = new com.toedter.calendar.JDateChooser();
        enDate = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        btn_timMa = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_seacrchText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rd_today = new javax.swing.JRadioButton();
        rd_otherDay = new javax.swing.JRadioButton();
        btn_timNgay = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_hoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Mã Hóa Đơn", "Tổng tiền hàng", "Giảm giá", "Khách đã trả", "Thời Gian(Thanh Toán)", "Người nhận đơn"
            }
        ));
        tb_hoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_hoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_hoaDon);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 750, 270));

        tb_hoaDonCt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sách", "Tên Sách", "Số Lượng", "Đơn Giá", "Thành Tiền"
            }
        ));
        tb_hoaDonCt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_hoaDonCtMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_hoaDonCt);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 750, 280));

        btnXuatfile.setText("xuất file");
        btnXuatfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatfileActionPerformed(evt);
            }
        });
        jPanel1.add(btnXuatfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 30, -1, -1));

        jButton2.setText("+ nhận đơn hàng");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, -1, -1));

        startDate.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(startDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 187, -1));

        enDate.setDateFormatString("dd/MM/yyyy");
        jPanel1.add(enDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 190, -1));

        jLabel1.setText("Từ ngày");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 58, 22));

        jLabel2.setText("Đến ngày");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 64, 22));

        jButton5.setText("In Hoa Don");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 30, -1, -1));

        btn_timMa.setText("Tìm Kiếm");
        btn_timMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timMaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_timMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        jLabel3.setText("Tìm Kiếm theo mã hóa đơn");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 190, -1));
        jPanel1.add(txt_seacrchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 90, 190, -1));

        jLabel4.setText("Thời Gian");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 190, 30));

        rd_today.setText("Hôm Nay");
        rd_today.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_todayActionPerformed(evt);
            }
        });
        jPanel1.add(rd_today, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 90, -1));

        rd_otherDay.setText("Chọn thời gian");
        rd_otherDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_otherDayActionPerformed(evt);
            }
        });
        jPanel1.add(rd_otherDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        btn_timNgay.setText("Tim Kiem");
        btn_timNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timNgayActionPerformed(evt);
            }
        });
        jPanel1.add(btn_timNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 720));

        jButton3.setText("Truoc");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 670, -1, -1));

        jButton4.setText("Sau");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 670, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_hoaDonCtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_hoaDonCtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_hoaDonCtMouseClicked

    private void tb_hoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_hoaDonMouseClicked
        // TODO add your handling code here:
        int row = tb_hoaDon.getSelectedRow();
        String idhd = tb_hoaDon.getValueAt(row, 0).toString();
        loadHoadonChiTiet(this.chiTietService.getAll(idhd));
    }//GEN-LAST:event_tb_hoaDonMouseClicked

    private void rd_todayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_todayActionPerformed
        // TODO add your handling code here:
        startDate.setEnabled(false);
        enDate.setEnabled(false);
        btn_timNgay.setEnabled(false);
        loadTableHoaDon(this.hoaDonService.getAll(this.getDate()));
    }//GEN-LAST:event_rd_todayActionPerformed

    private void rd_otherDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_otherDayActionPerformed
        // TODO add your handling code here:
        startDate.setEnabled(true);
        enDate.setEnabled(true);
        btn_timNgay.setEnabled(true);
    }//GEN-LAST:event_rd_otherDayActionPerformed

    private void btn_timNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timNgayActionPerformed
        // TODO add your handling code here:

//         lay ra end date va start date
//lay ngay bat dau
        Date sdate = startDate.getDate();
        SimpleDateFormat sd = new SimpleDateFormat("yyyy/MM/dd");
        String formattedDate = sd.format(sdate);
        String startDate = formattedDate.toString();

//        lay ngay ket thuc
        Date edate = enDate.getDate();
        String formattedendDate = sd.format(edate);
        String endDate = formattedendDate.toString();
        loadTableHoaDon((this.hoaDonService.getAllwithDate(startDate, endDate)));

    }//GEN-LAST:event_btn_timNgayActionPerformed

    private void btn_timMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timMaActionPerformed
        // TODO add your handling code here:
        String ma = txt_seacrchText.getText();
        loadTableHoaDon((this.hoaDonService.getonewithma(ma)));

    }//GEN-LAST:event_btn_timMaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int traLoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn in hóa đơn không", "In Hóa Đơn", JOptionPane.YES_NO_OPTION);
        int rowHD = tb_hoaDon.getSelectedRow();
        String maHD = tb_hoaDon.getValueAt(rowHD, 1).toString();
        if (traLoi == JOptionPane.YES_OPTION) {
            // Tạo một đối tượng JDialog
            JDialog dialog = new JDialog();
            dialog.setTitle("Thông tin thanh toán");
            dialog.setSize(400, 300);

            // Tạo một JTextArea
            JTextArea b = new JTextArea();
            b.setEditable(false); // Có thể chỉnh sửa nội dung trong JTextArea hay không
            dialog.add(b, BorderLayout.CENTER); // Đưa JTextArea vào vị trí trung tâm của JDialog

            // them noi dung bill vao day
            b.setText(b.getText() + "                                        Cửa Hàng Sach \n");
            b.setText(b.getText() + "-------------------------------------------------------------------------------\n");
            b.setText(b.getText() + "                                        Mã Hóa Đơn " + maHD + "\n");
            b.setText(b.getText() + "-------------------------------------------------------------------------------\n");
            b.setText(b.getText() + "  Sản Phẩm \tSố Lượng \tGiá \tThành Tiền" + "\n");
            b.setText(b.getText() + "--------------------------------------------------------------------------------\n");

            DefaultTableModel df = (DefaultTableModel) tb_hoaDonCt.getModel();

            // Lấy thông tin sản phẩm từ bảng
            for (int i = 0; i < tb_hoaDonCt.getRowCount(); i++) {
                String Name = df.getValueAt(i, 1).toString();
                String Qty = df.getValueAt(i, 2).toString();
                String Price = df.getValueAt(i, 3).toString();
                String Total = df.getValueAt(i, 4).toString();

                // Kiểm tra độ dài của tên sản phẩm
                if (Name.length() > 10) {
                    Name = Name.substring(0, 10) + "..."; // Giới hạn tên sản phẩm chỉ hiển thị 10 ký tự
                }

                b.setText(b.getText() + "  " + Name + "\t" + Qty + "\t" + Price + "\t" + Total + "\n");
            }

            b.setText(b.getText() + "--------------------------------------------------------------------------------\n");
            b.setText(b.getText() + "Tổng Tiền : \t\t\t" + tb_hoaDon.getValueAt(rowHD, 2) + "\n");
            b.setText(b.getText() + "--------------------------------------------------------------------------------\n");
            b.setText(b.getText() + "Cảm ơn quý khách!" + "\n");

            // Tạo một JButton
            JButton btnIn = new JButton("In Hóa Đơn");
            btnIn.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    try {
                        b.print();
                    } catch (PrinterException ex) {
                        Logger.getLogger(UIBanHang.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });
            dialog.add(btnIn, BorderLayout.SOUTH); // Đưa JButton vào vị trí dưới cùng của JDialog

            // Hiển thị JDialog
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnXuatfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatfileActionPerformed
        // TODO add your handling code here:
        try {
            XSSFWorkbook worbook = new XSSFWorkbook();
            XSSFSheet sheet = worbook.createSheet("Hoa Don");

            XSSFRow row = null;
            Cell cell = null;

            row = sheet.createRow(3);
            cell = row.createCell(0, CellType.NUMERIC);
            cell.setCellValue("STT");

            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("ID");

            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("Mã");

            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("Tổng Tiền Hàng");

            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue("Giam Giá");
            
            cell = row.createCell(5, CellType.STRING);
            cell.setCellValue("Khách Ðã Tra");
            
            cell = row.createCell(6, CellType.STRING);
            cell.setCellValue("Thoi Gian");
            
            cell = row.createCell(7, CellType.STRING);
            cell.setCellValue("Nguoi Nhân Ðon");
            List<HoaDonfinalViewModels> list = hoaDonService.getAll();

            if (list != null) {
                int s = list.size();
                for (int i = 0; i < s; i++) {
                    HoaDonfinalViewModels hd = list.get(i);
                    row = sheet.createRow(4 + i);

                    cell = row.createCell(0, CellType.NUMERIC);
                    cell.setCellValue(i + 1);
                    cell = row.createCell(01, CellType.STRING);
                    cell.setCellValue(hd.getId());
                    
                    cell = row.createCell(02, CellType.STRING);
                    cell.setCellValue(hd.getMa());
                    
                    cell = row.createCell(03, CellType.STRING);
                    cell.setCellValue(hd.getTongTien());
                    
                    cell = row.createCell(04, CellType.STRING);
                    cell.setCellValue(0);

                    cell = row.createCell(06, CellType.STRING);
                    cell.setCellValue(hd.getNgayTao().toString());

                    cell = row.createCell(05, CellType.STRING);
                    cell.setCellValue(hd.getKhachCanTra());

                    cell = row.createCell(07, CellType.STRING);
                    cell.setCellValue(hd.getTenNguoiDung());

                }
                File f = new File("E:\\FileThongKe.xlsx");
                try {
                    FileOutputStream fis = new FileOutputStream(f);

                    worbook.write(fis);
                    fis.close();
                } catch (FileNotFoundException e) {
                    e.printStackTrace();
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();

        }
        JOptionPane.showMessageDialog(this, "Xuất Thành Công");                        

    }//GEN-LAST:event_btnXuatfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXuatfile;
    private javax.swing.JButton btn_timMa;
    private javax.swing.JButton btn_timNgay;
    private com.toedter.calendar.JDateChooser enDate;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rd_otherDay;
    private javax.swing.JRadioButton rd_today;
    private com.toedter.calendar.JDateChooser startDate;
    private javax.swing.JTable tb_hoaDon;
    private javax.swing.JTable tb_hoaDonCt;
    private javax.swing.JTextField txt_seacrchText;
    // End of variables declaration//GEN-END:variables
}
