/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import domainmodels.KhachHang;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.KhachHangService;
import serviceimpl.KhachHangServiceImpl;

/**
 *
 * @author Huyên
 */
public class UIKhachHang extends javax.swing.JFrame {

    /**
     * Creates new form UIKhachHang
     */
    public UIKhachHang() {
        super("UIKhachHang");
        initComponents();
        setLocationRelativeTo(null);
        LoadToTable(khachHangService.getAll());
        rdio_Dang_HD1.setSelected(true);
        rdio_Dang_HD.setSelected(true);
        
    }

    KhachHangService khachHangService = new KhachHangServiceImpl();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        btnSua = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        txtTen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSoDt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rdio_Dang_HD = new javax.swing.JRadioButton();
        rdio_Ngung_HD = new javax.swing.JRadioButton();
        txtTenTim = new javax.swing.JTextField();
        rdio_Dang_HD1 = new javax.swing.JRadioButton();
        rdio_Ngung_HD1 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("KHACH HANG");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, -1));

        jLabel2.setText("ID Khách Hàng ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        txtId.setEnabled(false);
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 220, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "MÃ", "TÊN", "SÔ_DT", "EMAIL", "TRANG THÁI"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 1240, 280));

        btnThem.setText("THEM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel1.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 112, 30));

        jLabel3.setText("Mã Khách Hàng");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 90, 20));

        txtMa.setEnabled(false);
        jPanel1.add(txtMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 90, 230, -1));

        btnSua.setText("Cập Nhật Thông Tin");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, 112, 30));

        btnTimKiem.setText("TIM KIEM");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        jPanel1.add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 330, 140, 30));
        jPanel1.add(txtTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 220, 30));

        jLabel4.setText("Tên Khách Hàng");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 88, 30));

        jLabel5.setText("Số Điện Thoại");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 88, -1));
        jPanel1.add(txtSoDt, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 140, 230, 30));

        jLabel6.setText("EMAIL");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 88, 20));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 220, 30));

        jLabel7.setText("TRANG THAI");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, 88, 20));

        buttonGroup1.add(rdio_Dang_HD);
        rdio_Dang_HD.setText("Ðang hoạt động");
        jPanel1.add(rdio_Dang_HD, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, 130, 20));

        buttonGroup1.add(rdio_Ngung_HD);
        rdio_Ngung_HD.setText("Ngừng hoạt động");
        jPanel1.add(rdio_Ngung_HD, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 210, 144, 20));
        jPanel1.add(txtTenTim, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 290, 30));

        buttonGroup2.add(rdio_Dang_HD1);
        rdio_Dang_HD1.setText("Ðang hoạt động");
        rdio_Dang_HD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdio_Dang_HD1ActionPerformed(evt);
            }
        });
        jPanel1.add(rdio_Dang_HD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, 20));

        buttonGroup2.add(rdio_Ngung_HD1);
        rdio_Ngung_HD1.setText("Ngừng hoạt động");
        rdio_Ngung_HD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdio_Ngung_HD1ActionPerformed(evt);
            }
        });
        jPanel1.add(rdio_Ngung_HD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, 20));

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setText("All Data");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, 20));

        jButton1.setText("Trước");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 700, -1, -1));

        jButton2.setText("Tiếp theo");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 700, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 299, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String ten = txtTenTim.getText();
        System.out.println(ten);
        if (ten.equals("")) {
            JOptionPane.showMessageDialog(this, "Hay Nhap Ten Tim!");
            txtTenTim.requestFocus();
            return;
        } else {
            List<KhachHang> listSearch = this.khachHangService.timKiem(ten);
            LoadToTable(listSearch);
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        String id = txtId.getText();
        System.out.println(id);
        KhachHang kh = this.getData();
        System.out.println(kh);
        if (kh == null) {
            return;
        }
        JOptionPane.showMessageDialog(this, this.khachHangService.sua(kh, id));
        LoadToTable(khachHangService.getAll());
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        KhachHang khachHang = this.getData();
        if (khachHang == null) {
            return;
        }
        JOptionPane.showMessageDialog(this, this.khachHangService.add(khachHang));
        LoadToTable(khachHangService.getAll());
    }//GEN-LAST:event_btnThemActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        txtId.setText(table.getValueAt(row, 0).toString());
        txtMa.setText(table.getValueAt(row, 1).toString());
        txtTen.setText(table.getValueAt(row, 2).toString());
        txtSoDt.setText(table.getValueAt(row, 3).toString());
        txtEmail.setText(table.getValueAt(row, 4).toString());
        if (table.getValueAt(row, 5).toString().equals("Ðang hoạt động")) {
            rdio_Dang_HD.setSelected(true);
            rdio_Ngung_HD.setSelected(false);
        } else {
            rdio_Ngung_HD.setSelected(true);
            rdio_Dang_HD.setSelected(false);
        }
    }//GEN-LAST:event_tableMouseClicked

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        LoadToTable(khachHangService.getAll());
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void rdio_Dang_HD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdio_Dang_HD1ActionPerformed
        // TODO add your handling code here:
        LoadToTable(khachHangService.timKiemTT(0));
    }//GEN-LAST:event_rdio_Dang_HD1ActionPerformed

    private void rdio_Ngung_HD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdio_Ngung_HD1ActionPerformed
        // TODO add your handling code here:
        LoadToTable(khachHangService.timKiemTT(1));
    }//GEN-LAST:event_rdio_Ngung_HD1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public String checkTT(int tt) {
        if (tt == 0) {
            return "Ðang hoạt động";
        } else {
            return "Ngừng hoạt động";
        }
    }

    public String checktt(int tt) {
        if (tt == 1) {
            return "Ðang hoạt động";
        } else {
            return "Ngừng hoạt động";
        }
    }
    // check định dạng sdt

    private boolean validatePhoneNumber(String phoneNumber) {
        String regex = "^0[1-9]{9}$";
        return phoneNumber.matches(regex);
    }

//    kiem tra dinh dang email
    public static boolean isValidEmail(String email) {
        String regex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";
        return email.matches(regex);
    }

    public KhachHang getData() {
        String ten = txtTen.getText().trim();
        if (ten.equals("")) {
            JOptionPane.showMessageDialog(this, "Nhap ten!");
            txtTen.requestFocus();
            return null;
        }
        String soDt = txtSoDt.getText().trim();
        if (soDt.equals("") && soDt.isBlank() == false) {
            JOptionPane.showMessageDialog(this, "Nhap so dien thoai!");
            txtSoDt.requestFocus();
            return null;
        }
//        else if (this.validatePhoneNumber(soDt) == false &&soDt.isBlank() == false) {
//            JOptionPane.showMessageDialog(this, "So dien thoai khong dung dinh dang!");
//            txtSoDt.requestFocus();
//            return null;
//        }
        String email = txtEmail.getText().trim();
        if (email.equals("") && email.isBlank() == false) {
            JOptionPane.showMessageDialog(this, "Nhap so email!");
            txtEmail.requestFocus();
            return null;
        }
        if (isValidEmail(email) == false && email.isBlank() == false) {
            JOptionPane.showMessageDialog(this, "Email khong dung dinh dang!");
            txtEmail.requestFocus();
            return null;
        }

        if (rdio_Dang_HD.isSelected() == false && rdio_Ngung_HD.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "Chon trang thai");
            return null;
        }
        int trangThai = 0;
        if (rdio_Dang_HD.isSelected()) {
            trangThai = 0;
        } else {
            trangThai = 1;
        }

        KhachHang khachHang = new KhachHang(ten, soDt, email, trangThai);
        return khachHang;
    }

    public void LoadToTable(List<KhachHang> listKH) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        for (KhachHang khachHang : listKH) {
            model.addRow(new Object[]{
                khachHang.getId(), khachHang.getMa(), khachHang.getTen(), khachHang.getSoDt(), khachHang.getEmail(), checkTT(khachHang.getTrangThai())
            });
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIKhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdio_Dang_HD;
    private javax.swing.JRadioButton rdio_Dang_HD1;
    private javax.swing.JRadioButton rdio_Ngung_HD;
    private javax.swing.JRadioButton rdio_Ngung_HD1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtSoDt;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTenTim;
    // End of variables declaration//GEN-END:variables
}
