/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import domainmodels.NguoiDung;
import java.awt.Image;
import java.io.File;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.NguoiDungService;
import serviceimpl.NguoiDungServiceImpl;

/**
 *
 * @author User
 */
public class UINguoiDung extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    NguoiDungService nguoiDungService = new NguoiDungServiceImpl();
    String duongdananh;

    public UINguoiDung() {
        super("UINguoiDung");

        initComponents();
        LoadTableAll(nguoiDungService.getAll());
        ButtonGr();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txt_ma = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_ten = new javax.swing.JTextField();
        txt_Sdt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_matKhau = new javax.swing.JTextField();
        txt_diaChi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_nhanVien = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbb_gioiTinh = new javax.swing.JComboBox<>();
        cbb_chucVu = new javax.swing.JComboBox<>();
        cbb_trangThai = new javax.swing.JComboBox<>();
        lbl_image = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txt_email1 = new javax.swing.JTextField();
        jdate_ngSinh = new com.toedter.calendar.JDateChooser();
        rd_all = new javax.swing.JRadioButton();
        rd_dangHoatDong = new javax.swing.JRadioButton();
        rd_ngungHoatDong = new javax.swing.JRadioButton();
        txt_searchText = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_ma.setEnabled(false);
        jPanel1.add(txt_ma, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 169, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Quản lý Người Dùng");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 146, -1));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Chức Vụ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 70, -1));

        jLabel4.setText("HoTen");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 37, -1));
        jPanel1.add(txt_ten, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 169, -1));
        jPanel1.add(txt_Sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 169, -1));

        jLabel5.setText("Số điện thoại");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        jLabel6.setText("Mật Khẩu");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 70, -1));
        jPanel1.add(txt_matKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 169, -1));
        jPanel1.add(txt_diaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 169, -1));

        jLabel8.setText("Địa chỉ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 70, -1));

        jLabel9.setText("Email");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 37, -1));

        btn_add.setText("Thêm");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, -1, -1));

        btn_update.setText("Cập Nhật");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, -1, -1));

        tb_nhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã", "Họ tên", "SDT", "Mật Khẩu", "Địa chỉ", "Giới Tính", "Chức Vụ", "Trạng Thái", "Ngày Sinh", "Email", "Ảnh"
            }
        ));
        tb_nhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_nhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_nhanVien);
        if (tb_nhanVien.getColumnModel().getColumnCount() > 0) {
            tb_nhanVien.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 1330, 320));

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Ma");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 37, -1));

        jLabel10.setBackground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Ngày Sinh");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 70, -1));

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Giới Tinh");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 70, -1));

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Trạng thái");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 70, -1));

        cbb_gioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        jPanel1.add(cbb_gioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, 150, -1));

        cbb_chucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên", "Quản lý" }));
        jPanel1.add(cbb_chucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 150, -1));

        cbb_trangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang làm việc", "Ngừng làm việc" }));
        cbb_trangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_trangThaiActionPerformed(evt);
            }
        });
        jPanel1.add(cbb_trangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, 150, -1));

        lbl_image.setText("IMAGE");
        jPanel1.add(lbl_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, 170, 205));

        jButton3.setText("Chon anh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 270, 94, -1));

        jButton4.setText("previous");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 700, -1, -1));

        jButton5.setText("next");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 700, -1, -1));
        jPanel1.add(txt_email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 150, -1));

        jdate_ngSinh.setDateFormatString("yyyy/MM/dd ");
        jPanel1.add(jdate_ngSinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 150, -1));

        rd_all.setText("Tất cả");
        rd_all.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rd_allMouseClicked(evt);
            }
        });
        jPanel1.add(rd_all, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        rd_dangHoatDong.setText("Đang hoạt động");
        rd_dangHoatDong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rd_dangHoatDongMouseClicked(evt);
            }
        });
        rd_dangHoatDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_dangHoatDongActionPerformed(evt);
            }
        });
        jPanel1.add(rd_dangHoatDong, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        rd_ngungHoatDong.setText("Ngừng hoạt động");
        rd_ngungHoatDong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rd_ngungHoatDongMouseClicked(evt);
            }
        });
        jPanel1.add(rd_ngungHoatDong, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));
        jPanel1.add(txt_searchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 220, -1));

        btn_search.setText("Tìm kiếm theo tên");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        jPanel1.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    
    private void ButtonGr() {
        ButtonGroup bg = new ButtonGroup();
        bg.add(rd_all);
        bg.add(rd_dangHoatDong);
        bg.add(rd_ngungHoatDong);
        rd_all.setSelected(true);
    }
// lay ra trang thai

    private String getTrangThai(int TrangThai) {
        String trangThai;
        if (TrangThai == 0) {
            trangThai = "Đang làm việc";
        } else {
            trangThai = "Ngừng làm việc";
        }
        return trangThai;
    }

//     lay ra gioi tinh 0-nam, 1 nữ
    private String getGioiTinh(int gioiTinh) {
        String gioiTinhReturn;
        if (gioiTinh == 0) {
            gioiTinhReturn = "Nam";
        } else {
            gioiTinhReturn = "Nữ";
        }
        return gioiTinhReturn;
    }
// check định dạng sdt

    private boolean validatePhoneNumber(String phoneNumber) {
        String regex = "^[0-9]{10,11}$";
        return phoneNumber.matches(regex);
    }

//    kiem tra dinh dang email
    public static boolean isValidEmail(String email) {
        String regex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";
        return email.matches(regex);
    }
//    get one

    private NguoiDung getData() {
        String ten = txt_ten.getText().trim();
        if (ten.equals("")) {
            JOptionPane.showMessageDialog(this, "Khong de trong ten");
            return null;
        }
        String sdt = txt_Sdt.getText().trim();
        if (this.validatePhoneNumber(sdt) == false) {
            JOptionPane.showMessageDialog(this, "SDt khong hop le");
            return null;
        }
        String matKhau = txt_matKhau.getText().trim();
        if (matKhau.equals("")) {
            JOptionPane.showMessageDialog(this, "Khong de trong matkhau");
            return null;
        }
        String diaChi = txt_diaChi.getText().trim();
        if (diaChi.equals("")) {
            JOptionPane.showMessageDialog(this, "Khong de trong ten");
            return null;
        }
        String gioiTinhStr = cbb_gioiTinh.getSelectedItem().toString();
        int gioiTinh = 0;
        if (gioiTinhStr.equalsIgnoreCase("Nam")) {
            gioiTinh = 0;
        } else {
            gioiTinh = 1;
        }
        String chucVu = cbb_chucVu.getSelectedItem().toString();
        if (chucVu.equals("")) {
            JOptionPane.showMessageDialog(this, "Phải chọn chức vụ!");
            return null;
        }
        int trangThai = 0;
        String trangThaiStr = cbb_trangThai.getSelectedItem().toString();
        if (trangThaiStr.equalsIgnoreCase("Đang làm việc")) {
            trangThai = 0;
        } else {
            trangThai = 1;
        }
        Date date = jdate_ngSinh.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        String formattedDate = sdf.format(date);
        String ngaySinh = formattedDate.toString();
        String emial = txt_email1.getText().trim();
        if (emial.equals("") == false) {
            if (isValidEmail(emial) == false) {
                JOptionPane.showMessageDialog(this, "Email khong dung dinh dang!!");
                return null;
            }
        }
        String anh = null;
        if (duongdananh == null) {
            anh = null;
        } else {
            anh = duongdananh;
        }

        NguoiDung ng = new NguoiDung(ten, emial, gioiTinh, ngaySinh, diaChi, sdt, matKhau, chucVu, anh, trangThai);
        return ng;
    }

    public void LoadTableAll(List<NguoiDung> list) {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tb_nhanVien.getModel();
        defaultTableModel.setRowCount(0);
        for (int i = 0; i < list.size(); i++) {
            defaultTableModel.addRow(new Object[]{
                i + 1,
                list.get(i).getMa(),
                list.get(i).getHoTen(),
                list.get(i).getSdt(),
                list.get(i).getMatKhau(),
                list.get(i).getDiaChi(),
                getGioiTinh(list.get(i).getGioiTinh()),
                list.get(i).getChucVu(),
                getTrangThai(list.get(i).getTrangThai()),
                list.get(i).getNgaySinh(),
                list.get(i).getEmail(),
                list.get(i).getImage()
            });
        }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFileChooser f = new JFileChooser("D:\\Documents\\AnhSach");
        f.setDialogTitle("Chon file");
        f.showOpenDialog(null);
        File ftenanh = f.getSelectedFile();
        duongdananh = ftenanh.getAbsolutePath();
        System.out.println(duongdananh);
        if (duongdananh != null) {
            lbl_image.setIcon(ResizeImage(String.valueOf(duongdananh)));
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbb_trangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_trangThaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbb_trangThaiActionPerformed

    private void tb_nhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_nhanVienMouseClicked
        // TODO add your handling code here:
        int row = tb_nhanVien.getSelectedRow();
        txt_ma.setText(tb_nhanVien.getValueAt(row, 1).toString());
        txt_ten.setText(tb_nhanVien.getValueAt(row, 2).toString());
        txt_matKhau.setText(tb_nhanVien.getValueAt(row, 4).toString());
        txt_email1.setText(tb_nhanVien.getValueAt(row, 10).toString());
        txt_Sdt.setText(tb_nhanVien.getValueAt(row, 3).toString());
        lbl_image.setIcon(ResizeImage(String.valueOf(tb_nhanVien.getValueAt(row, 11))));
        txt_diaChi.setText(tb_nhanVien.getValueAt(row, 5).toString());
        cbb_chucVu.setSelectedItem(tb_nhanVien.getValueAt(row, 7));
        cbb_gioiTinh.setSelectedItem(tb_nhanVien.getValueAt(row, 6));
        cbb_trangThai.setSelectedItem(tb_nhanVien.getValueAt(row, 8));
        String dateString = tb_nhanVien.getValueAt(row, 9).toString(); // Lấy giá trị ngày tháng từ cột thứ 2 (ví dụ) của hàng đang được chọn
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date date = null;
        try {
            date = sdf.parse(dateString);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        jdate_ngSinh.setDate(date); // Đặt giá trị ngày tháng vào JDateChooser

    }//GEN-LAST:event_tb_nhanVienMouseClicked

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        NguoiDung nd = this.getData();
        if (nd == null) {
            return;
        }
        JOptionPane.showMessageDialog(rootPane, this.nguoiDungService.insert(nd));
        rd_all.setSelected(true);
        LoadTableAll(nguoiDungService.getAll());


    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:

        String ma = txt_ma.getText();
        NguoiDung nd = this.getData();
        if (nd == null) {
            return;
        }
        JOptionPane.showMessageDialog(rootPane, this.nguoiDungService.update(nd, ma));
        rd_all.setSelected(true);
        LoadTableAll(nguoiDungService.getAll());

    }//GEN-LAST:event_btn_updateActionPerformed

    private void rd_dangHoatDongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rd_dangHoatDongMouseClicked
        // TODO add your handling code here:
        System.out.println(" dang hoat dong hien thi table");
        LoadTableAll(this.nguoiDungService.getAllWithTrangThai(0));
    }//GEN-LAST:event_rd_dangHoatDongMouseClicked

    private void rd_allMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rd_allMouseClicked
        // TODO add your handling code here:
        LoadTableAll(nguoiDungService.getAll());
        System.out.println("load atble all");

    }//GEN-LAST:event_rd_allMouseClicked

    private void rd_ngungHoatDongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rd_ngungHoatDongMouseClicked
        // TODO add your handling code here:
        System.out.println(" load table ngung hoat dong");
        LoadTableAll(this.nguoiDungService.getAllWithTrangThai(1));

    }//GEN-LAST:event_rd_ngungHoatDongMouseClicked

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        String ten = txt_searchText.getText().trim();
        if (ten.equals("")) {
            JOptionPane.showMessageDialog(this, "Hay Nhap ten!");
            return;
        } else {
            List<NguoiDung> listSearch = this.nguoiDungService.search(ten);
            rd_all.setSelected(true);
            LoadTableAll(listSearch);
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void rd_dangHoatDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_dangHoatDongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_dangHoatDongActionPerformed
//   thay doi kich co anh sao cho vua  panel

    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon myImgae = new ImageIcon(ImagePath);
        Image img = myImgae.getImage();
        Image newImg = img.getScaledInstance(lbl_image.getWidth(), lbl_image.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UINguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UINguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UINguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UINguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UINguoiDung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbb_chucVu;
    private javax.swing.JComboBox<String> cbb_gioiTinh;
    private javax.swing.JComboBox<String> cbb_trangThai;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdate_ngSinh;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JRadioButton rd_all;
    private javax.swing.JRadioButton rd_dangHoatDong;
    private javax.swing.JRadioButton rd_ngungHoatDong;
    private javax.swing.JTable tb_nhanVien;
    private javax.swing.JTextField txt_Sdt;
    private javax.swing.JTextField txt_diaChi;
    private javax.swing.JTextField txt_email1;
    private javax.swing.JTextField txt_ma;
    private javax.swing.JTextField txt_matKhau;
    private javax.swing.JTextField txt_searchText;
    private javax.swing.JTextField txt_ten;
    // End of variables declaration//GEN-END:variables
}
