/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import domainmodels.NXB;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.NXBService;
import serviceimpl.NXBServiceImlp;

/**
 *
 * @author Huyên
 */
public class UINXB extends javax.swing.JFrame {

    /**
     * Creates new form UINXB
     */
    public UINXB() {
        initComponents();
        setLocationRelativeTo(null);
        LoadToTable(nxbService.getAll());
        rdio_dang_kd.setSelected(true);
        rdio_dang_kd1.setSelected(true);
    }

    private NXBService nxbService = new NXBServiceImlp();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtTen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_NXB = new javax.swing.JTable();
        rdio_dang_kd = new javax.swing.JRadioButton();
        rdio_ngung_kd = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        txtTenTim = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        rdio_dang_kd1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Quan Ly NXB");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 36, -1, -1));

        jLabel2.setText("ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 98, 100, 30));

        txtId.setEnabled(false);
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 98, 404, 30));

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(896, 76, 123, 40));

        jLabel3.setText("MA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 180, 100, -1));

        txtMa.setEnabled(false);
        jPanel1.add(txtMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 173, 404, 30));

        jButton2.setText("Sua");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(896, 184, 123, 35));

        jLabel4.setText("TÊN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 248, 100, 30));

        jButton3.setText("Tìm Kiêm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 390, 123, 30));
        jPanel1.add(txtTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 248, 404, 30));

        jLabel5.setText("TRANG THÁI");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 323, 100, 30));

        tbl_NXB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "MÃ", "TÊN", "TRẠNG THÁI"
            }
        ));
        tbl_NXB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_NXBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_NXB);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 1230, 260));

        buttonGroup1.add(rdio_dang_kd);
        rdio_dang_kd.setText("Ðang kinh doanh");
        jPanel1.add(rdio_dang_kd, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 321, -1, 35));

        buttonGroup1.add(rdio_ngung_kd);
        rdio_ngung_kd.setText("Ngừng kinh doanh");
        jPanel1.add(rdio_ngung_kd, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 321, -1, 35));

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setText("All data");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 377, 80, 28));
        jPanel1.add(txtTenTim, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 377, 30));

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("Ngừng Kinh Doanh");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 381, -1, -1));

        buttonGroup2.add(rdio_dang_kd1);
        rdio_dang_kd1.setText("Ðang kinh doanh");
        rdio_dang_kd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdio_dang_kd1MouseClicked(evt);
            }
        });
        rdio_dang_kd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdio_dang_kd1ActionPerformed(evt);
            }
        });
        jPanel1.add(rdio_dang_kd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 376, -1, 31));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        // TODO add your handling code here:
        LoadToTable(nxbService.getAll());
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void tbl_NXBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_NXBMouseClicked
        // TODO add your handling code here:
        int row = tbl_NXB.getSelectedRow();
        txtId.setText(tbl_NXB.getValueAt(row, 0).toString());
        txtMa.setText(tbl_NXB.getValueAt(row, 1).toString());
        txtTen.setText(tbl_NXB.getValueAt(row, 2).toString());
        if (tbl_NXB.getValueAt(row, 3).toString().equals("Ðang kinh doanh")) {
            rdio_dang_kd.setSelected(true);
            rdio_ngung_kd.setSelected(false);
        } else {
            rdio_dang_kd.setSelected(false);
            rdio_ngung_kd.setSelected(true);
        }
    }//GEN-LAST:event_tbl_NXBMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String ten = txtTenTim.getText().trim();
        if (ten.equals("")) {
            JOptionPane.showMessageDialog(this, "Hay nhap ten can tim!");
            txtTenTim.requestFocus();
            return;
        } else {
            List<NXB> listSearch = this.nxbService.timKiem(ten);
            LoadToTable(listSearch);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String id = txtId.getText();
        NXB nxb = this.getData();
        System.out.println("Nha xuat ban lay dươc: " + nxb);
        if (nxb == null) {
            return;
        }
        JOptionPane.showMessageDialog(this, this.nxbService.update(nxb, id));
        LoadToTable(nxbService.getAll());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        NXB nxb = this.getData();
        if (nxb == null) {
            return;
        }
        JOptionPane.showMessageDialog(this, this.nxbService.add(nxb));
        LoadToTable(nxbService.getAll());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rdio_dang_kd1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdio_dang_kd1MouseClicked
        // TODO add your handling code here:
        LoadToTable(nxbService.timKiemTT(0));
    }//GEN-LAST:event_rdio_dang_kd1MouseClicked

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
        // TODO add your handling code here:
        LoadToTable(nxbService.timKiemTT(1));
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void rdio_dang_kd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdio_dang_kd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdio_dang_kd1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public String checkTT(int tt) {
        if (tt == 0) {
            return "Ðang kinh doanh";
        } else {
            return "Ngừng kinh doanh";
        }
    }

    public int checktt(String tt) {
        if (tt.equals("Ðang kinh doanh")) {
            return 0;
        } else {
            return 1;
        }
    }

    public void LoadToTable(List<NXB> listTG) {
        DefaultTableModel model = (DefaultTableModel) tbl_NXB.getModel();
        model.setRowCount(0);
        for (NXB tg : listTG) {
            model.addRow(new Object[]{
                tg.getId(), tg.getMa(), tg.getTen(), checkTT(tg.getTrangthai())

            });
        }
    }

    public NXB getData() {
        String ten = txtTen.getText().trim();
        if (ten.equals("")) {
            JOptionPane.showMessageDialog(this, "Nhap ten!");
            txtTen.requestFocus();// tra vee nhap
            return null;
        }
        int trangThai = 0;

        if (rdio_dang_kd.isSelected()) {
            trangThai = 0;
        } else {
            trangThai = 1;
        }
        NXB nxb = new NXB(ten, trangThai);
        return nxb;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UINXB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UINXB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UINXB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UINXB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UINXB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdio_dang_kd;
    private javax.swing.JRadioButton rdio_dang_kd1;
    private javax.swing.JRadioButton rdio_ngung_kd;
    private javax.swing.JTable tbl_NXB;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTenTim;
    // End of variables declaration//GEN-END:variables
}
