/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import domainmodels.TheLoai;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import serviceimpl.svtheloaiimpl;
import service.svtheloai;

/**
 *
 * @author User
 */
public class UIQLtheloai extends javax.swing.JFrame {

    /**
     * Creates new form UIQLtheloai
     */
    private svtheloai svtheloai = new svtheloaiimpl();
    
    public UIQLtheloai() {
        initComponents();
        buttonGroup();
        LoadTable(svtheloai.getall());
        jRadioButton3.setSelected(true);
    }
    
    public void LoadTable(List<TheLoai> listTl) {
        DefaultTableModel model = (DefaultTableModel) tb_theLoai.getModel();
        model.setRowCount(0);
        for (TheLoai theLoai : listTl) {
            model.addRow(new Object[]{
                theLoai.getId(), theLoai.getMa(), theLoai.getTen(), getTrangThai(theLoai.getTrangthai())
            });
        }
    }
    
    public String getdate() {
        // lay ra ngay hien tai
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        return dtf.format(now);
    }
    
    void buttonGroup() {
        rd_dangkinhdoanh.setSelected(true);
        ButtonGroup btngr = new ButtonGroup();
        btngr.add(rd_dangkinhdoanh);
        btngr.add(rd_ngungkinhdaonh);
    }
    
    public String getTrangThai(int TrangThai) {
        String trangThai;
        if (TrangThai == 0) {
            trangThai = "Ðang kinh doanh";
        } else {
            trangThai = "Ngừng kinh doanh";
        }
        return trangThai;
    }
    
    public TheLoai getData() {
        String id = txt_idTheloai.getText().trim();
        String ma = txt_maTheLoai.getText().trim();
        String ten = txt_tenTheLoai.getText().trim();
        String ngayTao = this.getdate();
        String ngaySua = this.getdate();
        int trangThai = 0;
        if (rd_dangkinhdoanh.isSelected()) {
            trangThai = 0;
        } else {
            trangThai = 1;
        }
        if (ten.length() == 0 || ten.length() == 0) {
            JOptionPane.showMessageDialog(this, "Khong bo trong thon tin!");
            return null;
        }
        TheLoai s = new TheLoai(id, ma, ten, ngayTao, ngaySua, trangThai);
        return s;
    }
    
    public String checkTT(int tt) {
        if (tt == 1) {
            return "Ðang kinh doanh";
        } else {
            return "Ngừng kinh doanh";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_idTheloai = new javax.swing.JTextField();
        txt_maTheLoai = new javax.swing.JTextField();
        txt_tenTheLoai = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rd_dangkinhdoanh = new javax.swing.JRadioButton();
        rd_ngungkinhdaonh = new javax.swing.JRadioButton();
        btn_insert = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_theLoai = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_timkiem = new javax.swing.JButton();
        txtTenTim = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 67, 80, 35));

        jLabel3.setText("Mã TL");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 140, 80, 35));

        jLabel4.setText("Tên TL");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 210, 80, 35));

        txt_idTheloai.setEnabled(false);
        txt_idTheloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idTheloaiActionPerformed(evt);
            }
        });
        jPanel1.add(txt_idTheloai, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 73, 323, -1));

        txt_maTheLoai.setEnabled(false);
        jPanel1.add(txt_maTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 140, 323, 30));
        jPanel1.add(txt_tenTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 210, 323, 30));

        jLabel5.setText("Trạng Thái");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 288, 80, 35));

        rd_dangkinhdoanh.setText("Đang kinh doanh");
        rd_dangkinhdoanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_dangkinhdoanhActionPerformed(evt);
            }
        });
        jPanel1.add(rd_dangkinhdoanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, 35));

        rd_ngungkinhdaonh.setText("Ngừng kinh doanh");
        rd_ngungkinhdaonh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_ngungkinhdaonhActionPerformed(evt);
            }
        });
        jPanel1.add(rd_ngungkinhdaonh, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, -1, 35));

        btn_insert.setText("Thêm");
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });
        jPanel1.add(btn_insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 70, 112, 31));

        btn_update.setText("Câp Nhât");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 150, 112, 31));

        tb_theLoai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Mã TL", "Tên TL", "Trang Thai"
            }
        ));
        tb_theLoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_theLoaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_theLoai);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 1260, 350));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Quan ly the loai");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        btn_timkiem.setText("Tìm Kiêm");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });
        jPanel1.add(btn_timkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 380, 113, 35));
        jPanel1.add(txtTenTim, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 295, 32));

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setText("All Data");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("Ngừng Kinh Doanh");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("Ðang Kinh Doanh");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 344, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idTheloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idTheloaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idTheloaiActionPerformed

    private void rd_dangkinhdoanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_dangkinhdoanhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_dangkinhdoanhActionPerformed

    private void rd_ngungkinhdaonhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_ngungkinhdaonhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_ngungkinhdaonhActionPerformed

    private void tb_theLoaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_theLoaiMouseClicked
        // TODO add your handling code here:
        int row = tb_theLoai.getSelectedRow();
        txt_idTheloai.setText((String) tb_theLoai.getValueAt(row, 0));
        txt_maTheLoai.setText((String) tb_theLoai.getValueAt(row, 1));
        txt_tenTheLoai.setText((String) tb_theLoai.getValueAt(row, 2));
        
        if (tb_theLoai.getValueAt(row, 3).toString().equalsIgnoreCase("Ðang kinh doanh")) {
            rd_dangkinhdoanh.setSelected(true);
        } else {
            rd_ngungkinhdaonh.setSelected(true);
        }
    }//GEN-LAST:event_tb_theLoaiMouseClicked

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed
        // TODO add your handling code here:
        TheLoai tl = this.getData();
        if (tl == null) {
            return;
        }
        JOptionPane.showMessageDialog(this, svtheloai.insert(tl));
        LoadTable(svtheloai.getall());
    }//GEN-LAST:event_btn_insertActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        TheLoai tl = this.getData();
        if (tl == null) {
            return;
        }
        String id = txt_idTheloai.getText();
        JOptionPane.showMessageDialog(this, svtheloai.update(tl, id));
        LoadTable(svtheloai.getall());

    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        // TODO add your handling code here:
        String ten = txtTenTim.getText().trim();
        if (ten.equals("")) {
            JOptionPane.showMessageDialog(this, "Hay Nhap Ten Can Tim!");
            txtTenTim.requestFocus();
            return;
        } else {
            List<TheLoai> listSearch = this.svtheloai.timKiem(ten);
            DefaultTableModel defaultTableModel = (DefaultTableModel) tb_theLoai.getModel();
            defaultTableModel.setRowCount(0);
            for (int i = 0; i < svtheloai.timKiem(ten).size(); i++) {
                defaultTableModel.addRow(new Object[]{
                    i + 1,
                    svtheloai.timKiem(ten).get(i).getId(),
                    svtheloai.timKiem(ten).get(i).getMa(),
                    svtheloai.timKiem(ten).get(i).getTen(),
                    getTrangThai(svtheloai.timKiem(ten).get(i).getTrangthai())
                });
            }
        }
    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        LoadTable(svtheloai.getall());
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        LoadTable(svtheloai.timKiemTT(1));
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        LoadTable(svtheloai.timKiemTT(0));
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIQLtheloai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIQLtheloai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIQLtheloai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIQLtheloai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIQLtheloai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_insert;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JButton btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rd_dangkinhdoanh;
    private javax.swing.JRadioButton rd_ngungkinhdaonh;
    private javax.swing.JTable tb_theLoai;
    private javax.swing.JTextField txtTenTim;
    private javax.swing.JTextField txt_idTheloai;
    private javax.swing.JTextField txt_maTheLoai;
    private javax.swing.JTextField txt_tenTheLoai;
    // End of variables declaration//GEN-END:variables
}
