create database NHOM8_SACH
use NHOM8_SACH
go

-- 1 table sach
IF OBJECT_ID('SACH') IS NOT NULL
DROP TABLE SACH
GO
CREATE TABLE SACH(
	ID int Identity not null,
	Ma VARCHAR(20) UNIQUE DEFAULT DBO.AUTO_MASACH() ,
	TENSACH nvarchar(80),
	TRANGTHAI INT DEFAULT 0
	CONSTRAINT PK_SACH PRIMARY KEY(ID) 
	)
-- auto ma sach
CREATE FUNCTION AUTO_MASACH()
RETURNS VARCHAR(10)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT(ma) FROM sach) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(ma, 3)) FROM sach
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'SA00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'SA0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
--2 create TacGia
CREATE TABLE TACGIA (
ID int identity PRIMARY KEY ,
Ma VARCHAR(20) UNIQUE DEFAULT DBO.AUTO_MATG() ,
TEN NVARCHAR(50) DEFAULT NULL,
TRANGTHAI INT DEFAULT 0
)

-- FUNCTION AUTO MATG
CREATE FUNCTION AUTO_MATG()
RETURNS VARCHAR(10)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT(ma) FROM TACGIA) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(ma, 3)) FROM TACGIA
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'TG00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'TG0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
-- 3 SACH_TACGIA
IF OBJECT_ID('SACH_TACGIA') IS NOT NULL
DROP TABLE SACH_TACGIA
GO
CREATE TABLE SACH_TACGIA
(
ID_TG int NOT NULL,
ID_SACH int NOT NULL,
CONSTRAINT FK_SACHTG_SACH FOREIGN KEY(ID_SACH) REFERENCES SACH,
CONSTRAINT FK_SACHTG_TACGIA FOREIGN KEY(ID_TG) REFERENCES TACGIA,
CONSTRAINT PK_SACHTG PRIMARY KEY(ID_SACH,ID_TG)
)
--4 the loai
CREATE TABLE THELOAI(
ID int identity PRIMARY KEY ,
MA VARCHAR(20) UNIQUE  DEFAULT DBO.AUTO_MATL() ,
TEN NVARCHAR(50) DEFAULT NULL,
TRANGTHAI INT DEFAULT 0
)

-- AUTO MATHELOAI
CREATE FUNCTION AUTO_MATL()
RETURNS VARCHAR(5)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT(MA) FROM THELOAI) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MA, 3)) FROM THELOAI
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'TL00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'TL0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
 -- 5 table sach_theloai
IF OBJECT_ID('SACH_THELOAI') IS NOT NULL
DROP TABLE SACH_THELOAI
GO
CREATE TABLE SACH_THELOAI(
	ID_SACH int not null,
	ID_TL int not null,
	CONSTRAINT PK_SACHTL PRIMARY KEY(ID_sach,ID_TL) ,
	CONSTRAINT FK_SachTL_SACH FOREIGN KEY(ID_sach) REFERENCES SACH(ID),
	CONSTRAINT FK_SACHTL_Theloai FOREIGN KEY(ID_TL) REFERENCES THELOAI(ID)
	)

--6 table nxb
CREATE TABLE NXB(
ID int identity PRIMARY KEY ,
Ma VARCHAR(20) UNIQUE  DEFAULT DBO.AUTO_MANXB() ,
TEN NVARCHAR(50) DEFAULT NULL,
TRANGTHAI INT DEFAULT 0
)

-- FUNCTION AUTO MANXB
CREATE FUNCTION AUTO_MANXB()
RETURNS VARCHAR(5)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT(MA) FROM NXB) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MA, 3)) FROM NXB
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'NX00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'NX0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
--7 nguoidung

IF OBJECT_ID('NGUOIDUNG') IS NOT NULL
DROP TABLE NGUOIDUNG 
GO
CREATE TABLE NGUOIDUNG(
ID int identity PRIMARY KEY ,
MA VARCHAR(20) UNIQUE DEFAULT DBO.AUTO_MAND(),
HOTEN NVARCHAR(30) DEFAULT NULL,
EMAIL NVARCHAR(30) DEFAULT NULL,
GIOITINH BIT DEFAULT 0,
NGAYSINH DATE DEFAULT NULL,
DIACHI NVARCHAR(100) DEFAULT NULL,
SDT VARCHAR(30) DEFAULT NULL,
MATKHAU VARCHAR(MAX) DEFAULT NULL,
CHUCVU Nvarchar(10),
Image varchar(50) null,
TRANGTHAI bit DEFAULT 0
)
alter table nguoidung
alter column image nvarchar(100)
CREATE FUNCTION AUTO_MAND()
RETURNS VARCHAR(5)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT(MA) FROM NguoiDung) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MA, 3)) FROM NguoiDung
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'ND00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'ND0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
--8 khach hang
CREATE TABLE KHACHHANG(
	ID int identity PRIMARY KEY ,
	MAKH VARCHAR(5) UNIQUE DEFAULT DBO.AUTO_MAKH(),
	HOTEN NVARCHAR(50) NOT NULL,
	SDT VARCHAR(11) NULL,
	EMAIL VARCHAR(50) NULL,
	TRANGTHAI bit DEFAULT 0
)
CREATE FUNCTION AUTO_MAKH()
RETURNS VARCHAR(5)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT(MAKH) FROM KHACHHANG) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MAKH, 3)) FROM KHACHHANG
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'KH00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'KH0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
--9 HOADON
IF OBJECT_ID('HOADON') IS NOT NULL
DROP TABLE HOADON
GO
CREATE TABLE HOADON(
ID INT IDENTITY PRIMARY KEY ,
IDKH INT,
IDND INT,
MA VARCHAR(20) UNIQUE DEFAULT DBO.AUTO_MAHD(),
TONGTIEN decimal(5,2),
IDKHUYENMAI INT,
TONGTIENSAUKHUYENMAI DECIMAL(5,2),
NgayTao DATE DEFAULT NULL,
TrangThai BIT DEFAULT 0,
)
CREATE FUNCTION AUTO_MAHD()
RETURNS VARCHAR(5)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT(MA) FROM HOADON) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MA, 3)) FROM HOADON
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'HD' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'HD' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
--10 HOADONCHITIET

IF OBJECT_ID('HOADONCT') IS NOT NULL
DROP TABLE HOADONCT 
GO
CREATE TABLE HOADONCT(
ID INT IDENTITY PRIMARY KEY,
IDSACHCT INT,
IDHD INT,
DonGia DECIMAL(20,0),
SoLuong INT,
THANHTIEN DECIMAL(20,0)
)
--11 SACH CHI TIET
IF OBJECT_ID('SACHCT') IS NOT NULL
DROP TABLE SACHCT 
GO
CREATE TABLE SACHCT(
ID INT IDENTITY PRIMARY KEY ,
IDSACH INT,
IdNXB INT,
MOTA NVARCHAR(50) DEFAULT NULL,
GIANHAP DECIMAL(20,0) DEFAULT 0,
GIABAN DECIMAL(20,0) DEFAULT 0,
TRANGTHAI BIT DEFAULT 0,
IMAGE varchar(50),
MAVACH varchar(50)
)
--12 KHUYEN MAI
IF OBJECT_ID('KHUYENMAI') IS NOT NULL
DROP TABLE KHUYENMAI
GO
CREATE TABLE KHUYENMAI
(
	ID int Identity PRIMARY KEY not null,
	MAKM VARCHAR(20),
	TENKM nvarChar(100),
	CHIETKHAU INT ,
	NGAYAPDUNG DATETIME,
	NGAYKETTHUC DATETIME,
	TRANGTHAI bit DEFAULT 0
)
CREATE FUNCTION AUTO_MAKM()
RETURNS VARCHAR(5)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT(MA) FROM HOADON) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MA, 3)) FROM HOADON
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'HD' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'HD' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
-- MOI QUAN HE GIUA CAC BANG
-- SACH-SACHCT
ALTER TABLE SACHCT ADD FOREIGN KEY (IDSACH) REFERENCES Sach(ID)
-- SAHCCT-NNXB
ALTER TABLE SACHCT ADD FOREIGN KEY (IdNXB) REFERENCES NXB(Id)
-- HoaDonBan - NguoiDung
ALTER TABLE HoaDon ADD FOREIGN KEY(IDND) REFERENCES NguoiDung(Id)
-- HoaDonBan - KhachHang
ALTER TABLE HoaDon ADD FOREIGN KEY(IdKH) REFERENCES KhachHang(Id)
-- ChiTietHoaDon - SachChiTiet
ALTER TABLE HoaDonCT ADD FOREIGN KEY(IdSachCT) REFERENCES SachCT(Id)
-- ChiTietHoaDon - HoaDonBan
ALTER TABLE HoaDonCT ADD FOREIGN KEY(IdHD) REFERENCES HoaDon(Id)
-- HOADON-KHUYENMAI
ALTER TABLE HoaDon ADD FOREIGN KEY(IDKHUYENMAI) REFERENCES KHUYENMAI(Id)